export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
// const CHECKOUT;
// const PRODUCTS_LOADING_PENDING;
// const PRODUCTS_LOADING_SUCCESSFUL;
// const PRODUCTS_LOADING_FAILED;
